# Generated by Django 4.2.4 on 2023-09-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
