# Generated by Django 4.2.4 on 2023-09-04 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_project_image_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_key', models.CharField(max_length=255)),
                ('envato_key', models.CharField(max_length=255)),
                ('min_image', models.IntegerField()),
                ('max_size', models.IntegerField()),
                ('search_tags', models.IntegerField()),
                ('h2_start_from', models.IntegerField()),
                ('api_delay', models.IntegerField()),
                ('image_width', models.FloatField()),
                ('block_quote_per_article', models.IntegerField()),
                ('bolded_quote_per_article', models.IntegerField()),
                ('image_prompt', models.TextField()),
                ('block_quote', models.TextField()),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
