# Generated by Django 4.2.4 on 2023-09-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_image_folder_projectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_folder',
        ),
    ]
