# Generated by Django 4.2.4 on 2023-09-12 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_project_image_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
            ],
            options={
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.batch'),
        ),
    ]
