# Generated by Django 4.2.4 on 2023-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='old_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
