# Generated by Django 4.2.4 on 2023-09-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_article_new_json_alter_article_old_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='api_delay',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='block_quote_per_article',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='bolded_quote_per_article',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='h2_start_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='max_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='min_image',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='search_tags',
            field=models.PositiveIntegerField(),
        ),
    ]
