# Generated by Django 4.2.4 on 2023-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_article_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
